/*
DISTINCT CLAUSE -> USED TO GET UNIQUE ROWS
SELECT DISTINCT column_1 FROM TABLE
*/

-- DISTINCT USING 1 COL
-- SELECT DISTINCT first_name FROM contacts ORDER BY first_name;

-- DISTINCT USING 2 COL
-- SELECT DISTINCT product_id, quantity FROM order_items ORDER BY product_id;

-- using DISTINCT with NULL
-- SELECT DISTINCT STATE FROM LOCATIONS ORDER BY STATE NULLS LAST;